In [1]:
import numpy as np


In [2]:
mylist = [1, 2, 3, 4]

In [3]:
np.array(mylist)

array([1, 2, 3, 4])

In [4]:
mylist

[1, 2, 3, 4]

In [5]:
type(mylist)

list

In [6]:
arr = np.array(mylist)
type(arr)

numpy.ndarray

In [7]:
arr

array([1, 2, 3, 4])

In [8]:
a = np.arange(0, 10)

In [9]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
a = np.arange(0, 10, 2)

In [11]:
a

array([0, 2, 4, 6, 8])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.zeros((1,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
type(1.0)

float

In [21]:
type(1.)

float

In [22]:
type(1)

int

In [23]:
np.random.randint(0,100)

69

In [25]:
np.random.randint(0,100)

9

In [26]:
np.random.randint(0,100)

43

In [27]:
np.random.randint(0,100, (5,5))

array([[10, 60, 20, 94, 81],
       [30, 61, 42, 41, 13],
       [84, 93, 89, 20, 87],
       [71, 68, 59, 49, 56],
       [21, 13, 36, 96, 13]])

In [28]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [29]:
np.linspace(0, 10, 101) ##Linear Space format(범위의 시작, 범위의 끝, 생성할 요소의 갯수)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [30]:
np.linspace(0, 10, 200)

array([ 0.        ,  0.05025126,  0.10050251,  0.15075377,  0.20100503,
        0.25125628,  0.30150754,  0.35175879,  0.40201005,  0.45226131,
        0.50251256,  0.55276382,  0.60301508,  0.65326633,  0.70351759,
        0.75376884,  0.8040201 ,  0.85427136,  0.90452261,  0.95477387,
        1.00502513,  1.05527638,  1.10552764,  1.15577889,  1.20603015,
        1.25628141,  1.30653266,  1.35678392,  1.40703518,  1.45728643,
        1.50753769,  1.55778894,  1.6080402 ,  1.65829146,  1.70854271,
        1.75879397,  1.80904523,  1.85929648,  1.90954774,  1.95979899,
        2.01005025,  2.06030151,  2.11055276,  2.16080402,  2.21105528,
        2.26130653,  2.31155779,  2.36180905,  2.4120603 ,  2.46231156,
        2.51256281,  2.56281407,  2.61306533,  2.66331658,  2.71356784,
        2.7638191 ,  2.81407035,  2.86432161,  2.91457286,  2.96482412,
        3.01507538,  3.06532663,  3.11557789,  3.16582915,  3.2160804 ,
        3.26633166,  3.31658291,  3.36683417,  3.41708543,  3.46

In [31]:
np.random.seed(101) ##시드를 설정한다. 특정 시드값이 사용되면 다음에 만들어지는 난수들을 예측할 수 있음.

In [32]:
np.random.randint(0, 100, 10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [33]:
arr = np.random.randint(0, 100, 10)

In [34]:
arr

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [36]:
arr.max()

93

In [37]:
arr.min()

4

In [38]:
arr.min

<function ndarray.min>

In [39]:
arr.mean()

47.3

In [40]:
arr.argmax() ## 'arg' returns index value

8

In [41]:
arr.argmin()

0

In [45]:
arr.reshape(2,5)   ##reshape 은 형태를 재조정

array([[ 4, 63, 40, 60, 92],
       [64,  5, 12, 93, 40]])

In [47]:
mat = np.arange(0, 100).reshape(10, 10)

In [48]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [50]:
mat[5,2]

52

In [52]:
mat[:,2]  ##Call back every single column that index is '2'

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [53]:
mat[2, :] ##Call back every single row that index is '2'

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [54]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [55]:
mat > 50  ##Return boolean values

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [57]:
mat[mat>50] ##Return True Value which are satisfying condition

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [59]:
mat[mat>50].reshape(7,7)

array([[51, 52, 53, 54, 55, 56, 57],
       [58, 59, 60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78],
       [79, 80, 81, 82, 83, 84, 85],
       [86, 87, 88, 89, 90, 91, 92],
       [93, 94, 95, 96, 97, 98, 99]])